In [172]:
# -*- coding: utf-8 -*-

%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [173]:
# Data Source : http://www.statiz.co.kr/

picher_file_path = '../data/picher_stats_2017.csv'
batter_file_path = '../data/batter_stats_2017.csv'
picher = pd.read_csv(picher_file_path)
batter = pd.read_csv(batter_file_path)

In [174]:
import pandas as pd
from sklearn.linear_model import LinearRegression

# 데이터 로드
batter = pd.read_csv(batter_file_path)

# 선택한 feature로 데이터 준비
selected_features = ['타수', '안타', '홈런', '볼넷']
X = batter[selected_features]
y = batter['연봉(2017)']

# Linear Regression 모델 생성 및 학습
model = LinearRegression()
model.fit(X, y)

# 2018년 데이터 준비
batter_2018 = pd.read_csv(batter_file_path)
X_2018 = batter_2018[selected_features]

# 2018년 연봉 예측
y_pred = model.predict(X_2018)

# 예측 결과 출력
result_df = pd.DataFrame({'선수명': batter_df['선수명'], '예측연봉(2018)': y_pred})
print(result_df)

     선수명     예측연봉(2018)
0     최정  108720.644981
1    최형우  103796.228374
2    박건우   58183.814391
3    나성범   65040.536726
4    손아섭   82063.119605
..   ...            ...
186  김민식    5213.644306
187  장민석    3199.509441
188  채은성    2976.260710
189  김주형    1533.299473
190  이동훈    -405.362507

[191 rows x 2 columns]

In [175]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


# 원래의 데이터 프레임을 다시 로드합니다.
batter = pd.read_csv(batter_file_path)
batter = batter[['선수명', '연봉(2017)']]

# 원래의 데이터 프레임에 2018년 연봉 정보를 합칩니다.
#result_df = picher_df.sort_values(by=['y'], ascending=False)
result_df = batter_df
result_df.drop(['연봉(2017)'], axis=1, inplace=True, errors='ignore')
result_df = result_df.merge(batter, on=['선수명'], how='left')
result_df = result_df[['선수명', 'y', '예측연봉(2018)', '연봉(2017)']]
result_df.columns = ['선수명', '실제연봉(2018)', '예측연봉(2018)', '작년연봉(2017)']

X = result_df[['작년연봉(2017)']]  
y = result_df['실제연봉(2018)']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)


# 재계약하여 연봉이 변화한 선수만을 대상으로 관찰합니다.
result_df = result_df[result_df['작년연봉(2017)'] != result_df['실제연봉(2018)']]
result_df = result_df.reset_index()
result_df = result_df.iloc[:10, :]
result_df.head(10)

   index   선수명  실제연봉(2018)    예측연봉(2018)  작년연봉(2017)
0      2   박건우       37000  34465.298952       19500
1      3   나성범       43000  29107.904004       35000
2      4   손아섭      150000   3273.712440       65000
3      5   김선빈       28000  76364.051361        8000
4      7   박민우       32000   5034.890831       25000
5      8   김하성       32000   2241.692767       22000
6      9  스크럭스       70000   5420.163062       80000
7     10    러프      140000  28797.901892      110000
8     11   구자욱       25000   2748.248228       16000
9     12   안치홍       32000   4234.426448       22000